config/routes.rb
Rails.application.routes.draw do
  # --------------------------------------------------------------------------------
  # api/*
  # --------------------------------------------------------------------------------
  namespace :api do
    namespace :pin do
      post :all
      post :add
      post :remove
      post :clear
    end

    namespace :feed do
      match :discover, via: [:get, :post]
      post :subscribe
      post :unsubscribe
      match :subscribed, via: [:get, :post]
      post :update
      post :move
      post :set_rate
      post :set_notify
      post :set_public
      post :add_tags
      post :remove_tags
      post :fetch_favicon
    end

    namespace :item do
      get :items_test
    end

    namespace :folder do
      post :create
      post :delete
      post :update
    end

    namespace :config do
      match :load, action: :getter, via: [:post, :get]
      post  :save, action: :setter
    end

    %w(all unread touch_all touch item_count unread_count crawl).each do |name|
      match name, via: [:get, :post]
    end

    %w[subs lite_subs error_subs folders].each do |name|
      post name
    end
  end

  # other API call routes to blank page
  match 'api/*_' => 'application#nothing', via: [:post, :get]

  # --------------------------------------------------------------------------------
  # other pages
  # --------------------------------------------------------------------------------
  namespace :subscribe do
    get '', action: :index, as: :index
    get '*url', action: :confirm, format: false
    post '*url', action: :subscribe, format: false, as: nil
  end

  namespace :about do
    get '*url', action: :index, format: false
  end

  namespace :user do
    get ':login_name', action: :index
  end

  namespace :favicon do
    get '*feed', action: :get
  end

  resource :members, only: :create
  get 'signup', to: 'members#new', as: :sign_up

  resource :session, only: :create
  get 'login', to: 'sessions#new',     as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  root to: 'reader#welcome'

  get 'reader', to: 'reader#index'

  namespace :contents do
    get :guide
    get :config, action: :configure
    get :manage
  end

  get 'share', to: 'share#index', as: 'share'

  namespace :import do
    get '', action: :index
    post '', action: :fetch
    get '*url', action: :fetch, format: false
    post :finish
  end

  namespace :export do
    get :opml, as: ''
  end

  namespace :account do
    get '', action: :index, as: :index
    %w[apikey backup password share].each do |name|
      get name
    end
    post 'apikey'
  end

  namespace :rpc do
    %w[update_feed check_digest update_feeds export].each do |name|
      match name, via: [:post, :get]
    end
  end

  namespace :utility do
    namespace :bookmarklet do
      get '', action: :index
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :login_required
  layout false

  def guide
  end

  def configure
  end

  def manage
  end
end

app/views/contents/configure.html.slim
#config style="padding:0 10px;width:95%"
  h2 style="margin-top:0" Fastladder Settings
  = form_for :save, url: api_config_save_path, html: {id: "config_form", style: "clear: both; width: 100%; display: block;", onreset: "Form.fill(this, app.config); return false;"} do |f|
    .tabs
      #tab_config_basic.tab.tab-active rel="tab:config_form>config_basic" General
      #tab_config_view.tab rel="tab:config_form>config_view" Display
      #tab_config_pin.tab rel="tab:config_form>config_pin" Pin
      #tab_config_share.tab rel="tab:config_form>config_share" Share
      #tab_config_detail.tab rel="tab:config_form>config_detail" Detail
    #config_container style="clear:both; text-align: center;"
      #config_basic style="display:none"
        table
          tr
            th= link_to "Subscribe to feed", subscribe_path(url: "")
            td Click 'Add' icon and enter the feed URL.
          tr
            th= link_to "Manage subscription list", "#manage", onclick: "init_manage(); return false;"
            td Click 'Edit' icon to manage 'My Feeds'.
          tr.last
            th= link_to "Browser buttons", utility_bookmarklet_path
            td Add new feeds to your subscription list with an easy-access browser button.

      #config_view style="display:none"
        table
          tr
            th= f.label :current_font, "Font size"
            td
              = f.text_field :current_font, size: 4, name: "current_font"
              | px
          tr
            th Sort order
            td
              = f.label :reverse_mode_0 do
                = f.radio_button :reverse_mode, 0, name: "reverse_mode"
                | New articles first
              br
              = f.label :reverse_mode_1 do
                = f.radio_button :reverse_mode, 1, name: "reverse_mode"
                | Old articles first
          tr
            th Number of 'My Feeds' to show
            td
              p For shorter loading time, set the limit smaller.
              = f.label :use_limit_subs_1 do
                = f.radio_button :use_limit_subs, 1, name: "use_limit_subs"
                | Set limit to
                = f.text_field :limit_subs, value: 100, size: 4, name: "limit_subs"
                | feeds
              br
              = f.label :use_limit_subs_0 do
                = f.radio_button :use_limit_subs, 0, name: "use_limit_subs"
                | Display all
          tr
            th Highlight
            td
              | Highlight selected article when using keyboard shortcuts.
              br
              = f.label :use_scroll_hilight_1 do
                = f.radio_button :use_scroll_hilight, 1, name: "use_scroll_hilight"
                | Enable
              br
              = f.label :use_scroll_hilight_0 do
                = f.radio_button :use_scroll_hilight, 0, name: "use_scroll_hilight"
                | Diable
              br
          tr
            th= f.label :max_view, "Number of new articles per page"
            td
              | Number of articles to open when you first click on a feed.
              br
              = f.text_field :max_view, value: 200, name: "max_view", size: 4
              | articles (max: 200)
          tr
            th= f.label :items_per_page, "Number of old articles per page" 
              td
                | Number of articles to open when you click "older".
                br
                = f.text_field :items_per_page, value: 20, name: "items_per_page", size: 4
                | articles (max: 200)
      #config_detail style="display:none"
        table width="100%"
          tr
            th When to mark a feed as read
            td
              ul
                li
                  = f.label :touch_when_onload do
                    = f.radio_button :touch_when, "onload", name: "touch_when"
                    | Immediately after loading.
                li
                  = f.label :touch_when_onclose do
                    = f.radio_button :touch_when, "onclose", name: "touch_when"
                    | When moving to the next feed.
                li
                  = f.label :touch_when_manual do
                    = f.radio_button :touch_when, "manual", name: "touch_when"
                    | When marked as read.
          tr
            th Prefetching
            td
              | Set the number of feeds to prefetch
              br
              = f.label :use_prefetch_hack_1 do
                = f.radio_button :use_prefetch_hack, 1, name: "use_prefetch_hack"
                = f.text_field :prefetch_num, name: "prefetch_num", size: 2
                | items (max: 5)
              br
              = f.label :use_prefetch_hack_0 do
                = f.radio_button :use_prefetch_hack, 0, name: "use_prefetch_hack"
                | Use default setting
          tr
            th Scroll speed
            td
              | Scroll speed when using keyboard shortcuts
              br
              = f.label :use_wait_1 do
                = f.radio_button :use_wait, 1, name: "use_wait"
                | Enable: 
                = f.text_field :wait, value: 200, name: "wait", size: 6
                |  milliseconds
              br
              = f.label :use_wait_0 do
                = f.radio_button :use_wait, 0, name: "use_wait"
                | Disable
          tr
            th Scroll control
            td
              | Scroll unit (via space key)
              br
              = f.label :scroll_type_page do
                = f.radio_button :scroll_type, "page", name: "scroll_type"
                | One screen
              br
              = f.label :scroll_type_half do
                = f.radio_button :scroll_type, "half", name: "scroll_type"
                | Half screen
              br
              = f.label :scroll_type_px do
                = f.radio_button :scroll_type, "px", name: "scroll_type"
                | Precisely 
                = f.text_field :scroll_px, value: 100, name: "scroll_px", size: 6
                | px
          tr
            th Automatic update of 'My Feeds'
            td
              = f.label :use_autoreload_1 do
                = f.radio_button :use_autoreload, 1, name: "use_autoreload"
                | Enable: Reload every 
                = f.text_field :autoreload, name: "autoreload", size: 6
                | seconds. (min: 60 secs)
              br
              = f.label :use_autoreload_0 do
                = f.radio_button :use_autoreload, 0, name: "use_autoreload"
                | Disable
      #config_pin style="display:none"
        table width="100%"
          tr
            th Pin backup
            td
              | Let Fastladder remember your pin state (up to 100 changes).
              br
              = f.label :use_pinsaver_1 do
                = f.radio_button :use_pinsaver, 1, name: "use_pinsaver"
                | Enable
              br
              = f.label :use_pinsaver_0 do
                = f.radio_button :use_pinsaver, 0, name: "use_pinsaver"
                | Disable
          tr
            th= f.label :max_pin, "Open limitation"
            td
              | Open 
              = f.text_field :max_pin, name: "max_pin", size: 4
              |  tabs at a time.
          tr
            th Pop-up window
            td
              | To open articles with 'Pin' function, please set your browser to allow pop-ups on "#{reader_url}".
              br
              = link_to "Click on this link to test if pop-ups are enabled(3 new windows will open on success).", "#", onclick: "(3).times(function(){window.open()}); return false;"
      #config_share style="display:none"
        table width="100%"
          tr
            td colspan="2"
              p
                | To share your subscriptions with others, configure 
                = link_to "Manage Sharing", share_path
                | .
          tr
            th Sharing subscriptions
            td
              | If you enable sharing, others can read your public subscriptions at "#{user_url(current_member.username)}"
              - if current_member.public
                | (
                = link_to "Show public subscriptions", user_path(current_member.username)
                | )
              br
              = f.label :member_public_1 do
                = f.radio_button :member_public, 1, name: "member_public", checked: current_member.public
                | Enable Sharing
              br
              = f.label :member_public_0 do
                = f.radio_button :member_public, 0, name: "member_public", checked: !current_member.public
                | Disable Sharing
          tr
            th Default
            td
              | Default setting for new subscriptions
              br
              = f.label :default_public_status_1 do
                = f.radio_button :default_public_status, 1, name: "default_public_status"
                | Public
              br
              = f.label :default_public_status_0 do
                = f.radio_button :default_public_status, 0, name: "default_public_status"
                | Private
      #config_submit
        table
          tr.submit
            td style="text-align: center;"
              = f.button "Cancel", type: "reset"
              = f.submit "Save"
  h2 Import / Export Subscription List
  table.link
    tr
      th nowrap=true style="padding : 0 10px"
       = link_to "Import", import_path
      td Import OPML subscription list to Fastladder.
    tr
      th nowrap=true style="padding : 0 10px"
        = link_to "Export", export_path, download: "export.opml"
      td Create backup of current subscription list in OPML. Follow the link and select 'Save'.

app/views/contents/edit.html.erb
<%= form_for :feed, url: url_for(controller: "api/feed", action: "update"), html: {id: "subs_edit_form"} do |f| %>
<%= f.hidden_field :subscribe_id, name: "subscribe_id" %>
<%= f.hidden_field :api_key, name: "ApiKey", value: session[:session_id] %>
<table>
<tr>
	<th>Folder</th>
	<td><%= f.select :folder_id, [["Leave it uncategorized", "0"], ["Create new folder", "-"]], {}, id: "subs_edit_folder", name: "folder_id", onchange: "folder_change.call(this,event);" %></td>
</tr>
<tr>
	<th>Rating</th>
	<td><%= f.select :rate, %w/☆☆☆☆☆ ★☆☆☆☆ ★★☆☆☆ ★★★☆☆ ★★★★☆ ★★★★★/.zip(0..5), {}, name: "rate" %></td>
</tr>
<tr>
	<th>Share</th>
	<td>
		<%= f.radio_button :subs_edit_public, 1, id: "subs_edit_public_1", checked: @member.public %>
		<%= f.label :subs_edit_public_1, "Public", for: "subs_edit_public_1" %>
		<%= f.radio_button :subs_edit_public, 0, id: "subs_edit_public_0", checked: !@member.public %>
		<%= f.label :subs_edit_public_0, "Private", for: "subs_edit_public_0" %>
	</td>
</tr>
</table>
<div class="buttons">
	<span class="subs_edit_cancel" onclick="subs_edit.hide();">Close</span>
	<%= f.submit "Save" %>
</div>
<% end -%>

app/views/contents/guide.html.erb
<div class="guide">
<h2>Quick Guide</h2>

<h3>Subscribe your favorite blogs or news</h3>
<ul>
	<li>Install <%= link_to "browser buttons", utility_bookmarklet_path %> to add a new subscription from your browser.</li>
	<li>Click on 'Add' icon and enter the feed URL.</li>
	<li>You can <%= link_to "import your OPML subscription list", import_path %> to Fastladder.</li>
</ul>

<h3>Read items</h3>
<ul>
	<li>Use <% link_to "keyboard shortcut", "#", onclick: "Control.toggle_keyhelp(); return false" %> for lightning-fast readings.</li>
	<li>To read selected articles at once, use 'Pin' function to mark (hit 'P' or click <img src="/img/icon/pin.gif" alt="pin" /> on the upper-right corner of each article) and open (hit 'O' or click <img src="/img/icon/pin.gif" alt="pin" /> on the top tool bar).</li>
</ul>

<h3>Manage your subscriptions</h3>
<ul>
	<li>Categorize feeds by folders or your own ratings.</li>
	<li>Sort your feeds by variety of options (e.g. arrival time, title, rating, number of unread items or number of subscribers).</li>
</ul>

</div>

app/views/contents/manage.html.erb
<textarea class="template" id="man_item_header">
	<div id="manage_table" style="position:relative;">
	<table style="width:95%;margin:0 10px;clear:both">
	<tr>
		<th colspan="2" class="[[sortmode_title]]" rel="sort:title">Title</th>
		<th nowrap class="[[sortmode_unread_count]]" rel="sort:unread_count">Unreads</th>
		<th nowrap class="[[sortmode_folder]]" rel="sort:folder">Folder</th>
		<th nowrap class="[[sortmode_rate]]" rel="sort:rate">Rating</th>
		<th nowrap class="[[sortmode_modified_on]]" rel="sort:modified_on">Last update</th>
	</tr>
</textarea>
<textarea class="template" id="man_items">
	<tr class="[[classname]]" subscribe_id="[[subscribe_id]]" onmouseover="TRSelector.mouseover.call(this,event)" onmouseout="TRSelector.mouseout.call(this,event)" onmousedown="TRSelector.mousedown.call(this,event)">
		<td nowrap><img src="[[icon]]" width="16" height="16">
		<!--<img src="/img/icon/view.gif" width="21" height="16" class="button" onclick="preview([[subscribe_id]])">-->
		</td>
		<td><div style="width:300px;overflow:hidden">[[title]]</div></td>
		<td>[[unread_count]]</td>
		<td>[[folder]]</td>
		<td>
			<span style="position:relative">
				<img class="rate_pad" src="/img/rate/pad/[[ rate ]].gif" sid="[[subscribe_id]]" onclick="Rate.click.call(this,event)" onmouseout="Rate.out.call(this,event)" onmousedown="Event.stop(event)" onmousemove="Rate.hover.call(this,event)">
			</span>
		</td>
		<td>[[ update ]]</td>
	</tr>
</textarea>

<textarea class="template" id="man_folder">
	<li class="button [[selected]]" onclick="MF.select([[id]])">[[folder]]</li>
</textarea>

<textarea class="template" id="man_offset">
	[[ selecter_name ]]<small style="font-weight:normal">&nbsp;&nbsp;|&nbsp;&nbsp;[[ start ]] - [[ end ]] of [[ size ]] items</small>
</textarea>


<textarea class="template" id="manage_form">
<form action="/api/folder/update" method="post" id="rename_form">
	<input type="text" name="name" value="[[folder_name]]" style="width:20em">
	<input type="hidden" name="folder_id" value="[[folder_id]]">
	<input type="submit" value="Rename Folder">
</form>
<form action="/api/folder/delete" method="post" id="delete_form">
	<input type="hidden" name="folder_id" value="[[folder_id]]">
	<input type="submit" value="Delete Folder">
</form>
</textarea>

<h2 class="manage_h" style="margin-top:10px">Edit Feeds</h2>

<!-- manage_folder -->
<div id="manage_foldertools" style="clear:both; margin:5px 10px;padding:5px 5px 5px 30px; background:url('/img/icon/close.gif') no-repeat 7px 5px;">
	<u class="button" onclick="MF.create_folder(updater('manage_folder'))">Create New Folder</u>
	<div id="update_folder" style="display:inline"></div>
</div>
<div style="margin:10px;padding:0px;position:relative;background:#f5f5f5;">
	<ul id="manage_folder" style="margin:0px"></ul>
	<br clear="all">
</div>

<br clear="all">

<h2 class="manage_h" style="margin-top:10px"><span id="manage_offset"></span></h2>
<div style="font-size:12px;margin:10px 10px;">
<span id="manage_select"></span>
&nbsp;&nbsp;<span id="manage_help"></span>
</div>

<!-- manage_item -->
<div id="manage_control" class="grayout" style="clear:both;margin:5px 10px; background:url('/img/icon/default.gif') no-repeat 7px 9px; padding:5px 5px 0px 30px; vertical-align:bottom;">
<table>
<tr>
	<td valign="middle" nowrap>
	<select id="move_to">
	[[ folders ]]
	</select>
	<button onclick="Manage.Item.do_move()" title="Move to selected folder"
	 onmouseover="Manage.show_help.call(this,event)"
	 onmouseout="Manage.hide_help()"
	>Move to folder</button>
	</td>
	<td valign="middle">
	&nbsp;|&nbsp;
	<u class="button" title="Mark as read"
	 style="background:url('/img/icon/check.gif') no-repeat 0 2px;padding-left:20px"
	 onclick="this.disabled || MI.touch()"
	 onmouseover="Manage.show_help.call(this,event)"
	 onmouseout="Manage.hide_help()"
	>Mark as read</u>
	&nbsp;&nbsp;|&nbsp;&nbsp;
	<u class="button" style="background:url('/img/icon/trash.gif') no-repeat 0 2px;padding-left:22px" title="Unsubscribe" onclick="this.disabled || MI.unsubscribe()"
	 onmouseover="Manage.show_help.call(this,event)"
	 onmouseout="Manage.hide_help()"
	>Unsubscribe</u>
	</td>
</tr>
</table>
</div>
<table width="95%" id="manage_item_tool">
<tr>
	<td width="200" height="32" nowrap>
		 Find :&nbsp;<input type="text" onkeyup="MI.search.call(this,event)" style="width:150px">
	</td>
	<td >Select :&nbsp;
		<span class="button" onclick="MI.select_all()" title="Select all">Select All</span>&nbsp;&nbsp;|&nbsp;&nbsp;
		<span class="button" onclick="MI.page_select()" title="Select / Unselect this page">Select this page</span>&nbsp;&nbsp;|&nbsp;&nbsp;
		<span class="button" onclick="MI.reverse_select()" title="Reverse">Reverse</span>&nbsp;&nbsp;|&nbsp;&nbsp;
		<span class="button" onclick="MI.clear_select()" title="Select None">None</span>
	</td>
	<td width="50" nowrap align="right">
		<select onchange="MI.perpage=(this.options[this.selectedIndex].value-0) || 20;update('manage_item')" style="font-size:1em">
			<option>items / page</option>
			<option value="10">10</option>
			<option value="20">20</option>
			<option value="50">50</option>
		</select>
	</td>
	<td width="50" nowrap align="right">
		<div id="mi_paging">
			<span onclick="MI.prev()" id="mi_prev" class="paging">&lt;</span>
			<span onclick="MI.next()" id="mi_next" class="paging">&gt;</span>
		</div>
	</td>
</tr>
</table>
<div id="manage_item" style="padding:0">
	<div class="wait" style="margin:0 10px">Loading ..</div>
</div>