config/routes.rb
Rails.application.routes.draw do
  # --------------------------------------------------------------------------------
  # api/*
  # --------------------------------------------------------------------------------
  namespace :api do
    namespace :pin do
      post :all
      post :add
      post :remove
      post :clear
    end

    namespace :feed do
      match :discover, via: [:get, :post]
      post :subscribe
      post :unsubscribe
      match :subscribed, via: [:get, :post]
      post :update
      post :move
      post :set_rate
      post :set_notify
      post :set_public
      post :add_tags
      post :remove_tags
      post :fetch_favicon
    end

    namespace :item do
      get :items_test
    end

    namespace :folder do
      post :create
      post :delete
      post :update
    end

    namespace :config do
      match :load, action: :getter, via: [:post, :get]
      post  :save, action: :setter
    end

    %w(all unread touch_all touch item_count unread_count crawl).each do |name|
      match name, via: [:get, :post]
    end

    %w[subs lite_subs error_subs folders].each do |name|
      post name
    end
  end

  # other API call routes to blank page
  match 'api/*_' => 'application#nothing', via: [:post, :get]

  # --------------------------------------------------------------------------------
  # other pages
  # --------------------------------------------------------------------------------
  namespace :subscribe do
    get '', action: :index, as: :index
    get '*url', action: :confirm, format: false
    post '*url', action: :subscribe, format: false, as: nil
  end

  namespace :about do
    get '*url', action: :index, format: false
  end

  namespace :user do
    get ':login_name', action: :index
  end

  namespace :favicon do
    get '*feed', action: :get
  end

  resource :members, only: :create
  get 'signup', to: 'members#new', as: :sign_up

  resource :session, only: :create
  get 'login', to: 'sessions#new',     as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  root to: 'reader#welcome'

  get 'reader', to: 'reader#index'

  namespace :contents do
    get :guide
    get :config, action: :configure
    get :manage
  end

  get 'share', to: 'share#index', as: 'share'

  namespace :import do
    get '', action: :index
    post '', action: :fetch
    get '*url', action: :fetch, format: false
    post :finish
  end

  namespace :export do
    get :opml, as: ''
  end

  namespace :account do
    get '', action: :index, as: :index
    %w[apikey backup password share].each do |name|
      get name
    end
    post 'apikey'
  end

  namespace :rpc do
    %w[update_feed check_digest update_feeds export].each do |name|
      match name, via: [:post, :get]
    end
  end

  namespace :utility do
    namespace :bookmarklet do
      get '', action: :index
    end
  end
end

app/controllers/import_controller.rb
class ImportController < ApplicationController
  before_action :login_required

  def index
  end

  def fetch
    @folders = Hash.new do |hash, key|
      hash[key] = []
    end
    @opml ||= begin
      if params[:opml].respond_to? :read
        opml = params[:opml].read.to_s
      elsif params[:url].present?
        opml = Fastladder.simple_fetch(url_from_path(:url))
      end
      Opml.new(opml)
    rescue
      nil
    end
    @opml.outlines.map(&:flatten).each do |outlines|
      folder_name = (first = outlines.first).outlines.present? ? first.attributes["title"] || first.attributes["text"] : ""
      @folders[folder_name] += outlines.select {|outline| outline.attributes["xml_url"].present? }.map do |outline|
        attributes = outline.attributes.dup
        feedlink = attributes["xml_url"]
        feed = Feed.find_by(feedlink: feedlink)
        item = {}
        item[:title] = attributes["title"] || attributes["text"] || feedlink
        item[:link] = attributes["url"] || attributes["html_url"] || feedlink
        item[:feedlink] = feedlink
        item[:subscribed] = feed.present? ? current_member.subscribed(feed) : false
        item
      end
    end if @opml.is_a? Opml
  end

  def finish
    titles = params[:titles]
    feedlinks = params[:feedlinks]
    check_for_subscribes = params[:check_for_subscribes]
    options = {quick: true}
    check_for_subscribes.select {|key, value| value == "1" }.keys.map do |i|
      title, feedlink = titles[i], feedlinks[i]
      folder_name, feedlink = feedlink.split(":", 2)
      folder = Folder.find_or_create_by(member_id: current_member.id, name: folder_name)
      @member.subscribe_feed(feedlink, options.merge(folder_id: folder.id, title: title))
    end
    redirect_to reader_path
  end
end

app/views/import/fetch.html.erb
<div id="content">
<script type="text/javascript">
function get_target(button){
	var id = button.id.replace("button_","");
	return _$("ul_" + id);
}

function selectfolder(event){
	Event.stop(event);
	var ul = get_target(this);
	if(!ul) return;
	var ck = ul.getElementsByTagName("input");
	var len = ck.length;
	for(var i=0;i<len;i++) ck[i].checked = true;
}

function unselectfolder(event){
	Event.stop(event);
	var ul = get_target(this);
	if(!ul) return;
	var ck = ul.getElementsByTagName("input");
	var len = ck.length;
	for(var i=0;i<len;i++) ck[i].checked = false;
}

function s_toggle(mode,tab){
	switchClass("registerbox", "show-"+mode);
	var tabs = _$("import_tab");
	foreach(tabs.getElementsByTagName("div"),function(el){
		el == tab ? addClass(tab,"tab-active") : removeClass(el, "tab-active")
	})
}
</script>
<div style="padding:5px 15px 0;text-align:left;">
	<h2 class="px18 guidesubttl" style="border:none">Subscription list</h2>
</div>

<% if @opml.present? -%>
<%= form_for :import, url: import_finish_path do |f| %>
<%= f.hidden_field :api_key, name: "ApiKey", value: session[:session_id] %>
<div id="registerbox" style="width:auto;margin:0 10px">
	<div id="import_tab" class="tabs" style="text-align:left;padding-left:15px;">
		<div class="tab tab-active" onclick="s_toggle('all',this)">All<span class="num">(<%= all_count = (all_items = @folders.values.flatten).length %>)</span></div>
		<div class="tab" onclick="s_toggle('not_subscribed',this)">Without Subscribed feed<span class="num">(<%= unsubscribe_count = all_items.reject {|item| item[:subscribed] }.length %>)</span></div>
		<div class="tab" onclick="s_toggle('subscribed',this)">Subscribed<span class="num">(<%= all_count - unsubscribe_count %>)</span></div>
	</div>

	<div class="importbox">
<% @folders.each_with_index do |(folder_name, items), i| %>
	<h3 class="px18 importttl">
		<%= folder_name.present? ? folder_name : "Uncategolized" %>
		<span style="font-size:12px;color:#05308c;font-weight:normal;padding-left:10px;">
			<span class="button" onclick="selectfolder.call(this,event)" id="button_<%= i %>">Select All</span>
			&nbsp;|&nbsp;
			<span class="button" onclick="unselectfolder.call(this,event)" id="button_<%= i %>">None</span>
		</span>
	</h3>

	<ul id="ul_<%= i %>">
	<% items.select {|item| item[:feedlink].present? }.each_with_index do |item, i| -%>
		<li class="<%= "not_" unless item[:subscribed]-%>subscribed">
		<% if item[:subscribed] -%>
			<%= link_to item[:title], item[:link] %>
			<span style="color: #f00;">[Subscribed]</span>
		<% else -%>
			<%= f.hidden_field :titles, name: "titles[#{i}]", value: item[:title] %>
			<%= f.hidden_field :links, name: "links[#{i}]", value: item[:link] %>
			<%= f.hidden_field :feedlinks, name: "feedlinks[#{i}]", value: "#{folder_name}:#{item[:feedlink]}" %>
			<%= f.check_box :check_for_subscribe, name: "check_for_subscribes[#{i}]", checked: true %>
			<%= link_to item[:title], item[:link] %>
		<% end -%>
		</li>
	<% end -%>
	</ul>
<% end -%>
</div>

<div style="width:100px;margin:15px auto 0;padding-bottom:5px;">
	<%= f.submit " Import " %>
</div>
<% end -%>
<% else -%>
	<p>invalid OPML</p>
<% end -%>
</div>

<% content_for :extract_header do -%>
<style type="text/css">
.button{
	cursor : pointer;
}
.subscribed a:link{
	color : #888;
	text-decoration : none;
}
.subscribed a:visited{
	color : #888;
	text-decoration : none;
}
/* show-subscribed */
.show-subscribed .subscribed{ display:block }
.show-subscribed .not_subscribed{ display:none }


/* show-not_subscribed */
.show-not_subscribed .subscribed{ display:none }
.show-not_subscribed .not_subscribed{ display:block }

.tabs{
	font-family:Arial, Helvetica, sans-serif;
	font-size : 13px;
	height : 22px;
}
.tabs .tab{
	float : left;
	height : 14px;
	padding : 4px 6px;
	margin-right : 6px;
	color : white;
	background : #2d5ea1;
	font-weight : bold;
	cursor : pointer;
}
.tabs .tab-active{
	background : #4889fd !important;
}
.tabs .num{
	font-family : monospace;
}
.importbox{
	border : 1px solid #4a89fb;
}
</style>
<% end -%>

app/views/import/index.html.erb
<div id="content">
	<h2>Import</h2>
	<p>Fastladder supports the importing of OPML format subscription list.</p>

	<%= form_for :import, html: {multipart: true} do |f| %>
	<h3>Upload OPML</h3>
	<div class="sub-content">
		<%= f.file_field :opml, name: "opml" %>
		<%= f.submit "Import" %>
	</div>

	<h3>URL Import</h3>
	<div class="sub-content">
		<%= f.text_field :url, name: "url", value: "http://", size: 50 %>
		<%= f.submit "Import" %>
	</div>
	<% end %>

	<div class="sub-content">
		<h4>Attension</h4>
		<p>If you have many subscription list, it takes time to import. Please wait to finish importing.</p>
	</div>
</div>