config/routes.rb
Rails.application.routes.draw do
  # --------------------------------------------------------------------------------
  # api/*
  # --------------------------------------------------------------------------------
  namespace :api do
    namespace :pin do
      post :all
      post :add
      post :remove
      post :clear
    end

    namespace :feed do
      match :discover, via: [:get, :post]
      post :subscribe
      post :unsubscribe
      match :subscribed, via: [:get, :post]
      post :update
      post :move
      post :set_rate
      post :set_notify
      post :set_public
      post :add_tags
      post :remove_tags
      post :fetch_favicon
    end

    namespace :item do
      get :items_test
    end

    namespace :folder do
      post :create
      post :delete
      post :update
    end

    namespace :config do
      match :load, action: :getter, via: [:post, :get]
      post  :save, action: :setter
    end

    %w(all unread touch_all touch item_count unread_count crawl).each do |name|
      match name, via: [:get, :post]
    end

    %w[subs lite_subs error_subs folders].each do |name|
      post name
    end
  end

  # other API call routes to blank page
  match 'api/*_' => 'application#nothing', via: [:post, :get]

  # --------------------------------------------------------------------------------
  # other pages
  # --------------------------------------------------------------------------------
  namespace :subscribe do
    get '', action: :index, as: :index
    get '*url', action: :confirm, format: false
    post '*url', action: :subscribe, format: false, as: nil
  end

  namespace :about do
    get '*url', action: :index, format: false
  end

  namespace :user do
    get ':login_name', action: :index
  end

  namespace :favicon do
    get '*feed', action: :get
  end

  resource :members, only: :create
  get 'signup', to: 'members#new', as: :sign_up

  resource :session, only: :create
  get 'login', to: 'sessions#new',     as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  root to: 'reader#welcome'

  get 'reader', to: 'reader#index'

  namespace :contents do
    get :guide
    get :config, action: :configure
    get :manage
  end

  get 'share', to: 'share#index', as: 'share'

  namespace :import do
    get '', action: :index
    post '', action: :fetch
    get '*url', action: :fetch, format: false
    post :finish
  end

  namespace :export do
    get :opml, as: ''
  end

  namespace :account do
    get '', action: :index, as: :index
    %w[apikey backup password share].each do |name|
      get name
    end
    post 'apikey'
  end

  namespace :rpc do
    %w[update_feed check_digest update_feeds export].each do |name|
      match name, via: [:post, :get]
    end
  end

  namespace :utility do
    namespace :bookmarklet do
      get '', action: :index
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @target_member = Member.where(username: params[:login_name]).first
    @subscriptions = @target_member.subscriptions.where(public: true).order("created_on DESC").limit(30) if @target_member.public
    respond_to do |format|
      format.html
      format.rss { render layout: false }
      format.opml { render layout: false }
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  def subscribe_button(feedlink)
    if current_member
      if (subs = current_member.check_subscribed(feedlink)).present?
        raw <<-EOS.strip_heredoc
          <span class="subscribed">[subscribed]</span>
          <button class="subs_edit" rel="edit:#{subs.id}" onkeydown="subs_edit.call(this,event)" onmousedown="subs_edit.call(this,event)" onclick="return false">edit</button>
        EOS
      else
        link_to "add", subscribe_path(url: feedlink), class: "subscribe"
      end
    end
  end
end

app/views/user/index.html.erb
<% if @target_member.public -%>
<% content_for :extract_header do -%>
<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="<%= user_path(@target_member.username, format: "rss") %>" />
<% end -%>
<% end -%>
<div id="content" class="page_user">
<h2>User Information</h2>
<div id="content-inner">
<div class="user_info">
	<h3><%= @target_member.username %></h3>
	<% if logged_in? and @target_member == current_member %>
	<% if @target_member.public -%>
	<p><%= link_to "Manage Sharing", share_path %></p>
	<% else -%>
	<p>Share-setting is disabled. This page is not accessible to others.<br />You may set publicity of your subscription from "<%= link_to "Manage Sharing", share_path %>"</p>
	<% end -%>
	<% end -%>

	<div class="user_stats">
		<ul>
			<li>Total Subscriptions : <span id="total_subscribe_count"><%= @target_member.total_subscribe_count %></span></li>
			<li>Public Subscriptions : <span id="public_subscribe_count"><%= @target_member.public_subscribe_count %></span></li> 
		</ul>
		<% if @target_member.public -%>
		<ul class="link_rss">
			<li><%= link_to "Read public subscriptions", "#recent_subscribed" %></li>
			<li>
				<%= link_to "import subscription list", import_path(url: user_url(@target_member.username, format: "opml")) %>
				<%= link_to image_tag("/img/icon/opml.gif", alt: "", border: "0"), user_path(@target_member.username, format: "opml") %>
			</li>
		</ul>
		<% end -%>
	</div>

	<% if @target_member.public and @subscriptions.present? -%>
	<div class="recent_subscribed" id="recent_subscribed">
		<h3>Recent Subscriptions</h3>
		<p>
			<%= @target_member.username %>'s recent public subscriptions.
			<%= subscribe_button(user_url(@target_member.username, format: "rss")) %>
		</p>
		<ul class="recent_feeds">
		<% @subscriptions.map {|subs| [subs, subs.feed] }.each_with_index do |(subs, feed), i| %>
			<li class="<%= i % 2 == 0 ? 'odd' : 'even' %>">
				<%= link_to feed.title, feed.link, class: "title", style: "background-image: url('#{favicon_path(feed.id)}');" %>
				<div class="description"><%= feed.description %></div>
				<ul class="info">
					<li class="date"><%= subs.created_on  %></li>
					<li><%= link_to disp_users(feed.subscribers_count), about_path(url: feed.feedlink) %></li>
					<li><%= subscribe_button(feed.feedlink) %></li>
				</ul>
				<div style="clear:left"></div>
			</li>
		<% end -%>
		</ul>
	</div>
	<% end -%>

</div>
</div>
</div><!-- /content -->
<div style="clear:both;"></div>

<script type="text/javascript">
var ApiKey = null;
</script>
<%= javascript_include_tag "subscribe" %>